
import glob
import json
import os
import re
import urllib.parse
import uuid
from typing import Optional

import instaloader
import requests
import yt_dlp

DOWNLOADS_DIR = os.path.join(os.path.dirname(__file__), "downloads")
COOKIE_FILE = os.path.join(os.path.dirname(__file__), "instagram_cookies.txt")
SESSION_FILE = os.path.join(os.path.dirname(__file__), "session.json")

os.makedirs(DOWNLOADS_DIR, exist_ok=True)


# ── Session Management ────────────────────────────────────

def save_session(session_id: str, csrf_token: str = "", ds_user_id: str = ""):
    """Save Instagram session cookies to a Netscape cookie file for yt-dlp."""
    # Save raw session data as JSON for reference
    session_data = {
        "sessionid": session_id,
        "csrftoken": csrf_token,
        "ds_user_id": ds_user_id,
    }
    with open(SESSION_FILE, "w") as f:
        json.dump(session_data, f)

    # Write Netscape cookie file format that yt-dlp understands
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by InstaDownloader",
        "",
    ]

    cookies = [
        ("sessionid", session_id),
        ("csrftoken", csrf_token),
        ("ds_user_id", ds_user_id),
    ]

    for name, value in cookies:
        if value:
            # Format: domain  domain_flag  path  secure  expiry  name  value
            lines.append(
                f".instagram.com\tTRUE\t/\tTRUE\t0\t{name}\t{value}"
            )

    with open(COOKIE_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")

    return True


def get_session_status() -> dict:
    """Check if a valid session is stored."""
    if not os.path.exists(SESSION_FILE):
        return {"authenticated": False, "message": "No session configured"}

    try:
        with open(SESSION_FILE) as f:
            data = json.load(f)
        session_id = data.get("sessionid", "")
        if session_id:
            # Mask the session ID for security
            masked = session_id[:4] + "..." + session_id[-4:] if len(session_id) > 8 else "****"
            return {
                "authenticated": True,
                "message": f"Session active (ID: {masked})",
                "ds_user_id": data.get("ds_user_id", ""),
            }
    except Exception:
        pass

    return {"authenticated": False, "message": "Invalid session data"}


def clear_session():
    """Remove stored session cookies."""
    for f in [COOKIE_FILE, SESSION_FILE]:
        if os.path.exists(f):
            os.remove(f)

# ── Instaloader Fallback ──────────────────────────────────

def _get_instaloader() -> instaloader.Instaloader:
    L = instaloader.Instaloader(quiet=True)
    if os.path.exists(SESSION_FILE):
        try:
            with open(SESSION_FILE) as f:
                sessionid = json.load(f).get("sessionid")
                if sessionid:
                    L.context._session.cookies.set("sessionid", sessionid, domain=".instagram.com")
        except Exception:
            pass
    return L

def _extract_info_instaloader(url: str) -> dict:
    path = urllib.parse.urlparse(url).path
    parts = [p for p in path.split("/") if p]
    if len(parts) >= 2 and parts[0] in ("p", "reel", "reels", "tv"):
        shortcode = parts[1]
    else:
        raise ValueError("Invalid Instagram URL for fallback extraction")
    
    L = _get_instaloader()
    post = instaloader.Post.from_shortcode(L.context, shortcode)
    title = (post.caption and post.caption.replace('\n', ' ')[:50] or "Instagram Media")
    
    media_type = "video" if post.is_video else "photo"
    if post.typename == "GraphSidecar":
        items = []
        for node in post.get_sidecar_nodes():
            items.append({
                "title": title,
                "thumbnail": node.display_url,
                "type": "video" if node.is_video else "photo",
                "duration": 0,
                "ext": "mp4" if node.is_video else "jpg",
                "url": node.video_url if node.is_video else node.display_url,
            })
        return {
            "title": post.caption and post.caption[:50] or "Instagram Carousel",
            "thumbnail": items[0]["thumbnail"] if items else post.url,
            "type": "carousel",
            "items": items,
            "item_count": len(items),
            "uploader": post.owner_username,
            "url": url,
        }

    return {
        "title": title,
        "thumbnail": post.url,
        "type": media_type,
        "duration": 0,
        "uploader": post.owner_username,
        "ext": "mp4" if post.is_video else "jpg",
        "url": url,
        "width": 1080,
        "height": 1080,
    }

def _download_media_instaloader(url: str, file_id: str) -> dict:
    path = urllib.parse.urlparse(url).path
    parts = [p for p in path.split("/") if p]
    if len(parts) >= 2 and parts[0] in ("p", "reel", "reels", "tv"):
        shortcode = parts[1]
    else:
        raise ValueError("Invalid Instagram URL for fallback download")
        
    L = _get_instaloader()
    post = instaloader.Post.from_shortcode(L.context, shortcode)
    title_safe = "".join(x for x in (post.caption or "Instagram_Media") if x.isalnum() or x in " _-")[:30]
    
    if post.typename == "GraphSidecar":
        files = []
        for i, node in enumerate(post.get_sidecar_nodes()):
            dl_url = node.video_url if node.is_video else node.display_url
            ext = "mp4" if node.is_video else "jpg"
            filename = f"{file_id}_carousel_{i}_{title_safe}.{ext}"
            filepath = os.path.join(DOWNLOADS_DIR, filename)
            
            r = requests.get(dl_url, stream=True)
            r.raise_for_status()
            with open(filepath, "wb") as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)
                    
            files.append({
                "filename": filename,
                "filepath": filepath,
                "type": "video" if node.is_video else "photo",
                "size": os.path.getsize(filepath),
            })
        return {
            "type": "carousel",
            "files": files,
            "count": len(files),
        }
    
    dl_url = post.video_url if post.is_video else post.url
    ext = "mp4" if post.is_video else "jpg"
    filename = f"{file_id}_{title_safe}.{ext}"
    filepath = os.path.join(DOWNLOADS_DIR, filename)

    r = requests.get(dl_url, stream=True)
    r.raise_for_status()
    with open(filepath, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)
            
    return {
        "filename": filename,
        "filepath": filepath,
        "type": "video" if post.is_video else "photo",
        "size": os.path.getsize(filepath),
    }


# ── yt-dlp Options ────────────────────────────────────────

def _base_opts() -> dict:
    """Base yt-dlp options shared across extract and download."""
    opts = {
        "quiet": True,
        "no_warnings": True,
        "no_color": True,
    }
    if os.path.exists(COOKIE_FILE):
        opts["cookiefile"] = COOKIE_FILE
    return opts


def is_valid_instagram_url(url: str) -> bool:
    """Validate that a URL is a legitimate Instagram post/reel URL."""
    pattern = r"https?://(www\.)?(instagram\.com|instagr\.am)/(p|reel|reels|tv)/[\w-]+"
    return bool(re.match(pattern, url.strip()))


def _detect_media_type(info: dict) -> str:
    """Determine the media type from yt-dlp extracted info."""
    url = info.get("webpage_url", "")
    if "/reel/" in url or "/reels/" in url:
        return "reel"

    if info.get("ext") in ("jpg", "jpeg", "png", "webp"):
        return "photo"
    if info.get("duration") and info.get("duration") > 0:
        return "video"
    if info.get("ext") in ("mp4", "webm", "mkv"):
        return "video"

    return "video"


def _find_downloaded_file(file_id: str) -> Optional[str]:
    """Find a downloaded file by its unique ID prefix in the downloads dir."""
    pattern = os.path.join(DOWNLOADS_DIR, f"{file_id}_*")
    matches = glob.glob(pattern)
    if matches:
        for m in matches:
            if not m.endswith(".part"):
                return m
        return matches[0]
    return None


def extract_info(url: str) -> dict:
    """
    Extract metadata from an Instagram URL without downloading.
    Returns: dict with title, thumbnail, type, duration, uploader, etc.
    """
    ydl_opts = {
        **_base_opts(),
        "skip_download": True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        if not info:
            raise ValueError("Could not extract information from URL")
    except Exception as e:
        error_msg = str(e).lower()
        if "no video" in error_msg or "unsupported url" in error_msg:
            return _extract_info_instaloader(url)
        raise e

    # Handle playlist/carousel posts
    entries = info.get("entries")
    if entries:
        items = []
        for entry in entries:
            items.append({
                "title": entry.get("title", "Instagram Media"),
                "thumbnail": entry.get("thumbnail", ""),
                "type": _detect_media_type(entry),
                "duration": entry.get("duration"),
                "ext": entry.get("ext", "mp4"),
                "url": entry.get("webpage_url", url),
            })
        return {
            "title": info.get("title", "Instagram Carousel"),
            "thumbnail": items[0]["thumbnail"] if items else "",
            "type": "carousel",
            "items": items,
            "item_count": len(items),
            "uploader": info.get("uploader", info.get("channel", "Unknown")),
            "url": url,
        }

    media_type = _detect_media_type(info)

    return {
        "title": info.get("title", "Instagram Media"),
        "thumbnail": info.get("thumbnail", ""),
        "type": media_type,
        "duration": info.get("duration"),
        "uploader": info.get("uploader", info.get("channel", "Unknown")),
        "ext": info.get("ext", "mp4"),
        "url": url,
        "width": info.get("width"),
        "height": info.get("height"),
    }


def download_media(url: str) -> dict:
    """
    Download media from an Instagram URL.
    Returns: dict with filename, filepath, and media type.
    """
    file_id = uuid.uuid4().hex[:10]

    ydl_opts = {
        **_base_opts(),
        "outtmpl": os.path.join(DOWNLOADS_DIR, f"{file_id}_%(title).50s.%(ext)s"),
        "format": "best",
        "writethumbnail": False,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)

        if not info:
            raise ValueError("Download failed — no info returned")
    except Exception as e:
        error_msg = str(e).lower()
        if "no video" in error_msg or "unsupported url" in error_msg:
            return _download_media_instaloader(url, file_id)
        raise e

    # Handle carousel / playlist
    entries = info.get("entries")
    if entries:
        files = []
        for entry in entries:
            filepath = ydl.prepare_filename(entry)
            if not os.path.exists(filepath):
                filepath = _find_downloaded_file(file_id) or filepath
            if os.path.exists(filepath):
                files.append({
                    "filename": os.path.basename(filepath),
                    "filepath": filepath,
                    "type": _detect_media_type(entry),
                    "size": os.path.getsize(filepath),
                })
        return {
            "type": "carousel",
            "files": files,
            "count": len(files),
        }

    # Single file
    filepath = ydl.prepare_filename(info)

    if not os.path.exists(filepath):
        base = os.path.splitext(filepath)[0]
        for ext in [".mp4", ".webm", ".jpg", ".jpeg", ".png", ".webp"]:
            candidate = base + ext
            if os.path.exists(candidate):
                filepath = candidate
                break

    if not os.path.exists(filepath):
        found = _find_downloaded_file(file_id)
        if found:
            filepath = found

    if not os.path.exists(filepath):
        raise FileNotFoundError(
            "Download completed but file could not be located. "
            "Your session may have expired — try updating your session cookie."
        )

    return {
        "filename": os.path.basename(filepath),
        "filepath": filepath,
        "type": _detect_media_type(info),
        "size": os.path.getsize(filepath),
    }


def cleanup_file(filepath: str):
    """Remove a downloaded file after it has been served."""
    try:
        if os.path.exists(filepath):
            os.remove(filepath)
    except OSError:
        pass
