
import glob
import os
import re
import urllib.parse
import uuid
from typing import Optional
from dotenv import load_dotenv

import instaloader
import requests
import yt_dlp

DOWNLOADS_DIR = os.path.join(os.path.dirname(__file__), "downloads")
COOKIE_FILE = os.path.join(os.path.dirname(__file__), "instagram_cookies.txt")

os.makedirs(DOWNLOADS_DIR, exist_ok=True)
load_dotenv()

SESSION_ID = os.getenv("INSTAGRAM_SESSIONID") or os.getenv("SESSIONID") or ""
CSRF_TOKEN = os.getenv("INSTAGRAM_CSRFTOKEN") or os.getenv("CSRFTOKEN") or ""
DS_USER_ID = os.getenv("INSTAGRAM_DS_USER_ID") or os.getenv("DS_USER_ID") or ""


# ── Session Management ────────────────────────────────────

def _sync_cookie_file_from_env() -> bool:
    """Build yt-dlp cookie file from environment variables."""
    if not SESSION_ID:
        if os.path.exists(COOKIE_FILE):
            os.remove(COOKIE_FILE)
        return False

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by InstaDownloader from environment variables",
        "",
    ]

    cookies = [
        ("sessionid", SESSION_ID),
        ("csrftoken", CSRF_TOKEN),
        ("ds_user_id", DS_USER_ID),
    ]

    for name, value in cookies:
        if value:
            # Format: domain  domain_flag  path  secure  expiry  name  value
            lines.append(
                f".instagram.com\tTRUE\t/\tTRUE\t0\t{name}\t{value}"
            )

    with open(COOKIE_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")
    return True


COOKIE_AUTH_ENABLED = _sync_cookie_file_from_env()


def get_session_status() -> dict:
    """Check if Instagram authentication is configured via environment vars."""
    if not SESSION_ID:
        return {
            "authenticated": False,
            "message": "No session configured in env vars",
        }

    masked = SESSION_ID[:4] + "..." + SESSION_ID[-4:] if len(SESSION_ID) > 8 else "****"
    return {
        "authenticated": COOKIE_AUTH_ENABLED,
        "message": f"Session active from env (ID: {masked})",
        "ds_user_id": DS_USER_ID,
    }

# ── Instaloader Fallback ──────────────────────────────────

def _get_instaloader() -> instaloader.Instaloader:
    L = instaloader.Instaloader(quiet=True)
    if SESSION_ID:
        L.context._session.cookies.set("sessionid", SESSION_ID, domain=".instagram.com")
    if CSRF_TOKEN:
        L.context._session.cookies.set("csrftoken", CSRF_TOKEN, domain=".instagram.com")
    if DS_USER_ID:
        L.context._session.cookies.set("ds_user_id", DS_USER_ID, domain=".instagram.com")
    return L

def _extract_info_instaloader(url: str) -> dict:
    path = urllib.parse.urlparse(url).path
    parts = [p for p in path.split("/") if p]
    if len(parts) >= 2 and parts[0] in ("p", "reel", "reels", "tv"):
        shortcode = parts[1]
    else:
        raise ValueError("Invalid Instagram URL for fallback extraction")
    
    L = _get_instaloader()
    post = instaloader.Post.from_shortcode(L.context, shortcode)
    title = (post.caption and post.caption.replace('\n', ' ')[:50] or "Instagram Media")
    
    media_type = "video" if post.is_video else "photo"
    if post.typename == "GraphSidecar":
        items = []
        for node in post.get_sidecar_nodes():
            items.append({
                "title": title,
                "thumbnail": node.display_url,
                "type": "video" if node.is_video else "photo",
                "duration": 0,
                "ext": "mp4" if node.is_video else "jpg",
                "url": node.video_url if node.is_video else node.display_url,
            })
        return {
            "title": post.caption and post.caption[:50] or "Instagram Carousel",
            "thumbnail": items[0]["thumbnail"] if items else post.url,
            "type": "carousel",
            "items": items,
            "item_count": len(items),
            "uploader": post.owner_username,
            "url": url,
        }

    return {
        "title": title,
        "thumbnail": post.url,
        "type": media_type,
        "duration": 0,
        "uploader": post.owner_username,
        "ext": "mp4" if post.is_video else "jpg",
        "url": url,
        "width": 1080,
        "height": 1080,
    }

def _download_media_instaloader(url: str, file_id: str) -> dict:
    path = urllib.parse.urlparse(url).path
    parts = [p for p in path.split("/") if p]
    if len(parts) >= 2 and parts[0] in ("p", "reel", "reels", "tv"):
        shortcode = parts[1]
    else:
        raise ValueError("Invalid Instagram URL for fallback download")
        
    L = _get_instaloader()
    post = instaloader.Post.from_shortcode(L.context, shortcode)
    title_safe = "".join(x for x in (post.caption or "Instagram_Media") if x.isalnum() or x in " _-")[:30]
    
    if post.typename == "GraphSidecar":
        files = []
        for i, node in enumerate(post.get_sidecar_nodes()):
            dl_url = node.video_url if node.is_video else node.display_url
            ext = "mp4" if node.is_video else "jpg"
            filename = f"{file_id}_carousel_{i}_{title_safe}.{ext}"
            filepath = os.path.join(DOWNLOADS_DIR, filename)
            
            r = requests.get(dl_url, stream=True)
            r.raise_for_status()
            with open(filepath, "wb") as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)
                    
            files.append({
                "filename": filename,
                "filepath": filepath,
                "type": "video" if node.is_video else "photo",
                "size": os.path.getsize(filepath),
            })
        return {
            "type": "carousel",
            "files": files,
            "count": len(files),
        }
    
    dl_url = post.video_url if post.is_video else post.url
    ext = "mp4" if post.is_video else "jpg"
    filename = f"{file_id}_{title_safe}.{ext}"
    filepath = os.path.join(DOWNLOADS_DIR, filename)

    r = requests.get(dl_url, stream=True)
    r.raise_for_status()
    with open(filepath, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            f.write(chunk)
            
    return {
        "filename": filename,
        "filepath": filepath,
        "type": "video" if post.is_video else "photo",
        "size": os.path.getsize(filepath),
    }


# ── yt-dlp Options ────────────────────────────────────────

def _base_opts() -> dict:
    """Base yt-dlp options shared across extract and download."""
    opts = {
        "quiet": True,
        "no_warnings": True,
        "no_color": True,
    }
    if os.path.exists(COOKIE_FILE):
        opts["cookiefile"] = COOKIE_FILE
    return opts


def is_valid_instagram_url(url: str) -> bool:
    """Validate that a URL is a legitimate Instagram post/reel URL."""
    pattern = r"https?://(www\.)?(instagram\.com|instagr\.am)/(p|reel|reels|tv)/[\w-]+"
    return bool(re.match(pattern, url.strip()))


def _detect_media_type(info: dict) -> str:
    """Determine the media type from yt-dlp extracted info."""
    url = info.get("webpage_url", "")
    if "/reel/" in url or "/reels/" in url:
        return "reel"

    if info.get("ext") in ("jpg", "jpeg", "png", "webp"):
        return "photo"
    if info.get("duration") and info.get("duration") > 0:
        return "video"
    if info.get("ext") in ("mp4", "webm", "mkv"):
        return "video"

    return "video"


def _find_downloaded_files(file_id: str) -> list[str]:
    """Find all downloaded files by their unique ID prefix in the downloads dir."""
    pattern = os.path.join(DOWNLOADS_DIR, f"{file_id}_*")
    matches = glob.glob(pattern)
    # Filter out .part files and sort them to maintain order
    valid_files = [m for m in matches if not m.endswith(".part")]
    valid_files.sort()
    return valid_files


def extract_info(url: str) -> dict:
    """
    Extract metadata from an Instagram URL without downloading.
    Returns: dict with title, thumbnail, type, duration, uploader, etc.
    """
    ydl_opts = {
        **_base_opts(),
        "skip_download": True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        if not info:
            raise ValueError("Could not extract information from URL")
    except Exception as e:
        error_msg = str(e).lower()
        if "no video" in error_msg or "unsupported url" in error_msg:
            return _extract_info_instaloader(url)
        raise e

    # Handle playlist/carousel posts
    entries = info.get("entries")
    if entries:
        items = []
        for entry in entries:
            items.append({
                "title": entry.get("title", "Instagram Media"),
                "thumbnail": entry.get("thumbnail", ""),
                "type": _detect_media_type(entry),
                "duration": entry.get("duration"),
                "ext": entry.get("ext", "mp4"),
                "url": entry.get("webpage_url", url),
            })
        return {
            "title": info.get("title", "Instagram Carousel"),
            "thumbnail": items[0]["thumbnail"] if items else "",
            "type": "carousel",
            "items": items,
            "item_count": len(items),
            "uploader": info.get("uploader", info.get("channel", "Unknown")),
            "url": url,
        }

    media_type = _detect_media_type(info)

    return {
        "title": info.get("title", "Instagram Media"),
        "thumbnail": info.get("thumbnail", ""),
        "type": media_type,
        "duration": info.get("duration"),
        "uploader": info.get("uploader", info.get("channel", "Unknown")),
        "ext": info.get("ext", "mp4"),
        "url": url,
        "width": info.get("width"),
        "height": info.get("height"),
    }


def download_media(url: str) -> dict:
    """
    Download media from an Instagram URL.
    Returns: dict with filename, filepath, and media type.
    """
    file_id = uuid.uuid4().hex[:10]

    ydl_opts = {
        **_base_opts(),
        "outtmpl": os.path.join(DOWNLOADS_DIR, f"{file_id}_%(playlist_index|0)s_%(title).50s.%(ext)s"),
        "format": "best",
        "writethumbnail": False,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)

        if not info:
            raise ValueError("Download failed — no info returned")
    except Exception as e:
        error_msg = str(e).lower()
        if "no video" in error_msg or "unsupported url" in error_msg:
            return _download_media_instaloader(url, file_id)
        raise e

    # Handle carousel / playlist
    entries = info.get("entries")
    if entries:
        files = []
        # First try to find files using prepare_filename
        for entry in entries:
            filepath = ydl.prepare_filename(entry)
            if os.path.exists(filepath):
                files.append({
                    "filename": os.path.basename(filepath),
                    "filepath": filepath,
                    "type": _detect_media_type(entry),
                    "size": os.path.getsize(filepath),
                })
        
        # If prepare_filename failed to find all files, fallback to glob
        if len(files) < len(entries):
            found_files = _find_downloaded_files(file_id)
            # Re-build files list if we found matches via glob that weren't captured
            if len(found_files) >= len(entries):
                files = []
                # Try to match found files back to entries
                for i, filepath in enumerate(found_files[:len(entries)]):
                    entry = entries[i] if i < len(entries) else entries[-1]
                    files.append({
                        "filename": os.path.basename(filepath),
                        "filepath": filepath,
                        "type": _detect_media_type(entry),
                        "size": os.path.getsize(filepath),
                    })
        
        return {
            "type": "carousel",
            "files": files,
            "count": len(files),
        }

    # Single file
    filepath = ydl.prepare_filename(info)

    if not os.path.exists(filepath):
        base = os.path.splitext(filepath)[0]
        for ext in [".mp4", ".webm", ".jpg", ".jpeg", ".png", ".webp"]:
            candidate = base + ext
            if os.path.exists(candidate):
                filepath = candidate
                break

    if not os.path.exists(filepath):
        found = _find_downloaded_files(file_id)
        if found:
            filepath = found[0]

    if not os.path.exists(filepath):
        raise FileNotFoundError(
            "Download completed but file could not be located. "
            "Your session may have expired — try updating your session cookie."
        )

    return {
        "filename": os.path.basename(filepath),
        "filepath": filepath,
        "type": _detect_media_type(info),
        "size": os.path.getsize(filepath),
    }


def cleanup_file(filepath: str):
    """Remove a downloaded file after it has been served."""
    try:
        if os.path.exists(filepath):
            os.remove(filepath)
    except OSError:
        pass
